### ISSUE TITLE
테스트 커버리지를 80% 이상으로 높인다.

### ISSUE THREAD

**Issue by JinJuMoon** [woowacourse-teams/2020-6rinkers#219]
## 목적
> 테스트 커버리지를 80% 이상으로 높인다.
## 작업 상세 내용
- [ ] 테스트 커버리지를 80% 이상으로 높인다.
## 참고 사항
exclude 설정을 제거했을 때의 현재 커버리지입니다.

<img width="1124" alt="스크린샷 2020-09-22 오후 5 57 56" src="https://user-images.githubusercontent.com/40536197/93862834-a0079b80-fcfd-11ea-8b38-1ece3ecb4a9d.png">

**Comment by toneyparky** [comment]
화이팅 💪
