### ISSUE TITLE
Ingredient의 title을 name으로 변경한다.

### ISSUE THREAD

**Issue by KimGyeong** [woowacourse-teams/2020-6rinkers#258]
## 목적
> 네이밍 통일성을 위해 필드 변수명을 변경한다.
## 작업 상세 내용
- [x] 도메인의 필드 변수명을 변경한다.
- [x] DTO의 필드 변수명을 변경한다.

**Comment by toneyparky** [comment]
UserRecipe에서 에러가 발생하여 버그 수정

mappedby 참조를 user_cocktail로 해줬었는데 userCocktail로 수정
